### ISSUE TITLE
Support for multiple languages?

### ISSUE THREAD

**Issue by vsoch** [SonarSource/sonar-custom-rules-examples#1]
Hi ! We have a code repo that has both Python and C, and would like to have tests run for both. Is there a way to specify this `sonar-project.properties`? Thanks!

**Comment by agigleux** [comment]
Hi,
This repo is there to demonstrate how to write custom rules for some of the SonarSource analyzers.
That's not the good place to ask general questions about how to configure your code scan.
You'd better ask that to http://stackoverflow.com/questions/tagged/sonarqube

**Comment by vsoch** [comment]
Sorry about that - we wound up not needing it. Thanks anyway!
