### ISSUE TITLE
Licensing for commercial use

### ISSUE THREAD

**Issue by d0m3k** [SonarSource/sonar-custom-rules-examples#12]
Hello all,
I am writing some custom Java rules for my job and I find example classes very helpful at designing setup for the plugin.
Unfortunately, I'm afraid of breaking licensing rules of LGPL, since the code, more or less deriving from this project, cannot be open sourced.

What is your opinion on the case?

**Comment by andrea-guarino-sonarsource** [comment]
Hello,
Sorry for the late response, we don't monitor GitHub issues and we will disable them soon on this repository. If you need help could you please open a thread on https://community.sonarsource.com/ instead?
