### ISSUE TITLE
the javascript example does not work

### ISSUE THREAD

**Issue by cwassert** [SonarSource/sonar-custom-rules-examples#19]
The tests run fine, but the generated plugin does not work at all.
The function `checkClasses()` in `JavaScriptCustomRulesDefinition` is executed, but neither `visitCallExpression()` nor `visitNode()` is ever called.
If I read the travis log correctly, SonarJS is not even installed on the sonarqube instance it uses.

Steps to reproduce:
1. `git clone https://github.com/SonarSource/sonar-custom-rules-examples.git`
2. `cd sonar-custom-rules-examples/javascript-custom-rules/`
3. `mvn package`
4. deploy `target/javascript-custom-rules-1.0-SNAPSHOT.jar`
5. `sonar-scanner -D sonar.host.url=http://localhost:9000/ -D sonar.projectKey=jstest -D sonar.sources=src/test/resources/checks`
6. The issues do not show up

**Comment by nilamjadhav** [comment]
Is there any update on this? I am facing same issue

**Comment by nilamjadhav** [comment]
We have to add profile for newly created rule and set that profile instead of sonar way.
https://docs.sonarqube.org/latest/instance-administration/quality-profiles/

**Comment by quentin-jaquier-sonarsource** [comment]
@nilamjadhav is right:

> We have to add profile for newly created rule and set that profile instead of sonar way.
> https://docs.sonarqube.org/latest/instance-administration/quality-profiles/

You are missing this step between 4 and 5 in order to see the issues. I tested this morning and it worked just fine!

By the way, this feature is deprecated since SonarJS 6.0, as a replacement, you can have a look at ESLint, it provides custom rules that you can then import thanks to the external issues feature.

**Comment by shiyu-Wang** [comment]
> We have to add profile for newly created rule and set that profile instead of sonar way.
> https://docs.sonarqube.org/latest/instance-administration/quality-profiles/

I tried, but doesn't work, issues can't show up still...
