### ISSUE TITLE
java.lang.IllegalStateException: At least one issue expected

### ISSUE THREAD

**Issue by tuxonfire** [SonarSource/sonar-custom-rules-examples#24]
Hello,
I'm trying to do some custom sonar rules for my static code, firstly I did a rule in order to avoid some imports of libraries in my java code, it works well. ie. import Java.io.* // Noncompliant  <- works good!.

Now I'm tryiing to do a check to my methods, and the following error appears constantly:

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.698 s <<< FAILURE! - in com.mycompany.rules.sonar.checks.AvoidClassesInMethodNamesRuleTest
[ERROR] test(com.mycompany.rules.sonar.checks.AvoidClassesInMethodNamesRuleTest)  Time elapsed: 3.423 s  <<< ERROR!
java.lang.IllegalStateException: At least one issue expected
[sonar-rules-plugin.zip](https://github.com/SonarSource/sonar-custom-rules-examples/files/2103210/sonar-rules-plugin.zip)

	at com.mycompany.rules.sonar.checks.AvoidClassesInMethodNamesRuleTest.test(AvoidClassesInMethodNamesRuleTest.java:32)

[INFO] Running com.mycompany.rules.sonar.JavaRulesDefinitionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.334 s - in com.myconpany.rules.sonar.JavaRulesDefinitionTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AvoidClassesInMethodNamesRuleTest.test:32 ? IllegalState At least one issue ex...
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO]

**Comment by miaoluy** [comment]
your test should contains at least one issue which you want to scan. and you must add this word " // Noncompliant {{XXX}}" after your issue-code in the same row.  XXX is which you define in your CheckClass like "context.reportIssue(this, tree, XXXXXXX)"

**Comment by andrea-guarino-sonarsource** [comment]
Hello,
Sorry for the late response, we don't monitor GitHub issues and we will disable them soon on this repository. If you need help could you please open a thread on https://community.sonarsource.com/ instead?
