### ISSUE TITLE
Java shows this rule after the custom rule installation, but the scan is fine

### ISSUE THREAD

**Issue by LIUSHUAI2018** [SonarSource/sonar-custom-rules-examples#25]
After packaging the Java rule code of the instance and putting it under the specified directory, sonar was restarted to scan a problematic project without scanning the problem

**Comment by tuxonfire** [comment]
I dont know if this issue is related to https://github.com/SonarSource/sonar-custom-rules-examples/issues/24 or something...

**Comment by andrea-guarino-sonarsource** [comment]
Hello,
Sorry for the late response, we don't monitor GitHub issues and we will disable them soon on this repository. If you need help could you please open a thread on https://community.sonarsource.com/ instead?
