### ISSUE TITLE
The s3318 rule in the source code rules is also an object in the javax package. Why can't the source code be scanned

### ISSUE THREAD

**Issue by LIUSHUAI2018** [SonarSource/sonar-custom-rules-examples#27]
I put the test class of s3318 rule in the source code package into the project, but with the source code s3318 rule, scan the project, scan the code of the test class

**Comment by andrea-guarino-sonarsource** [comment]
Hello,
Sorry for the late response, we don't monitor GitHub issues and we will disable them soon on this repository. If you need help could you please open a thread on https://community.sonarsource.com/ instead?
