### ISSUE TITLE
what's the problem of "org.sonar.sslr.grammar.GrammarException"

### ISSUE THREAD

**Issue by Poncgo** [SonarSource/sonar-custom-rules-examples#38]
i just clone the examples and run a test "AvoidAnnotationCheckTest".  the exception stack is :
Caused by: org.sonar.sslr.grammar.GrammarException: The rule 'f.newTuple20(Object, Object)' has already been defined somewhere in the grammar.
	at org.sonar.sslr.grammar.GrammarBuilder$RuleBuilder.is(GrammarBuilder.java:285)
	at com.sonar.sslr.impl.typed.GrammarBuilderInterceptor.replaceByRule(GrammarBuilderInterceptor.java:159)
	at com.sonar.sslr.api.typed.ActionParser$ActionMethodInterceptor.intercept(ActionParser.java:138)
	at org.sonar.java.ast.parser.TreeFactory$$EnhancerByCGLIB$$e89e6d4d.newTuple20(<generated>)
	at org.sonar.java.ast.parser.JavaGrammar.SWITCH_CASE_EXPRESSION_LIST(JavaGrammar.java:954)
	at org.sonar.java.ast.parser.JavaGrammar$$EnhancerByCGLIB$$727aa2b0.CGLIB$SWITCH_CASE_EXPRESSION_LIST$87(<generated>)
	at org.sonar.java.ast.parser.JavaGrammar$$EnhancerByCGLIB$$727aa2b0$$FastClassByCGLIB$$43a62551.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.sonar.sslr.impl.typed.GrammarBuilderInterceptor.intercept(GrammarBuilderInterceptor.java:76)
	at org.sonar.java.ast.parser.JavaGrammar$$EnhancerByCGLIB$$727aa2b0.SWITCH_CASE_EXPRESSION_LIST(<generated>)
	... 36 more
 anyone has encountered this problem?

**Comment by wnlhdx** [comment]
I have encountered this problem.Either when I  try to run write a new rule and test it or run the rule in this  examples.How can I resolve it?

**Comment by Poncgo** [comment]
i have changed  to 'sonar-java'

**Comment by TimTimir** [comment]
> i have changed to 'sonar-java'

Hello! Could you please explain, what exactly have you done to overcome this problem? What do you mean by "i have changed to 'sonar-java'"?

**Comment by Phips0812** [comment]
@Poncgo what do you mean by you have changed to 'sonar-java'?

**Comment by LeslieM98** [comment]
Any fix known so far? I rolled back to 3d78b954f4e1dc850bf3b711be1deb22bb1a414c to try out if the error was there already but that just gave me another error:
```
    Error:(40, 30) java: cannot find symbol
    symbol:   class Java
    location: package org.sonar.plugins.java" 
```
in this file https://github.com/SonarSource/sonar-custom-rules-examples/blob/3d78b954f4e1dc850bf3b711be1deb22bb1a414c/java-custom-rules/src/main/java/org/sonar/samples/java/MyJavaRulesDefinition.java#L40

**Comment by wujun8** [comment]
Anyone has succeed avoid this problem?
Should I run in another branch or what?

**Comment by wujun8** [comment]
It seems that you can not run a single test, but just run
```bash
mvn package
```
will do the trick,  it will run all the tests with maven-surefire-plugin.

**Comment by LeslieM98** [comment]
So basically inside the ide it does not work but when you do it manually in the terminal it does work?

**Comment by wujun8** [comment]
[**@LeslieM98**](https://github.com/LeslieM98) commented on [2019年8月1日 GMT+8 下午4:51](https://github.com/SonarSource/sonar-custom-rules-examples/issues/38#issuecomment-517192212 "2019-08-01T08:51:34Z - Replied by Github Reply Comments"):
> So basically inside the ide it does not work but when you do it manually in the terminal it does work?

No, you can also run maven goal inside the IDE.
What I mean is, in this project unit test can't run alone, but work with maven goals.

**Comment by wujun8** [comment]
Upgrading `sslr-testing-harness` to the latest version will do
```
<sslr.version>1.23</sslr.version>
```

**Comment by ikoopa** [comment]
i got the same problem too,it mybe version conflict.
my sonarqube is 7.6 ,change the "sonar.version"  to version 7.6, "sonarjava.version"  to version 5.0.1.12818 , will run no error.

`<sonar.version>7.7</sonar.version>                  
<sonarjava.version>5.12.1.17771</sonarjava.version> `

**Comment by slowwalkerlcr** [comment]
> 5.0.1.12818

how can i get the version of the relationship bettween <sonar.version> and <sonarjava.version>

**Comment by slowwalkerlcr** [comment]
> i got the same problem too,it mybe version conflict.
> my sonarqube is 7.6 ,change the "sonar.version" to version 7.6, "sonarjava.version" to version 5.0.1.12818 , will run no error.
> 
> `<sonar.version>7.7</sonar.version> <!-- 7.6 --> <sonarjava.version>5.12.1.17771</sonarjava.version> <!-- 5.0.1.12818 -->`

how can i get the version of the relationship bettween <sonar.version> and <sonarjava.version>

**Comment by slowwalkerlcr** [comment]
> i got the same problem too,it mybe version conflict.
> my sonarqube is 7.6 ,change the "sonar.version" to version 7.6, "sonarjava.version" to version 5.0.1.12818 , will run no error.
> 
> `<sonar.version>7.7</sonar.version> <!-- 7.6 --> <sonarjava.version>5.12.1.17771</sonarjava.version> <!-- 5.0.1.12818 -->`

how can i get the version of the relationship between <sonar.version> and <sonarjava.version>

> i got the same problem too,it mybe version conflict.
> my sonarqube is 7.6 ,change the "sonar.version" to version 7.6, "sonarjava.version" to version 5.0.1.12818 , will run no error.
> 
> `<sonar.version>7.7</sonar.version> <!-- 7.6 --> <sonarjava.version>5.12.1.17771</sonarjava.version> <!-- 5.0.1.12818 -->`

@ikoopa how can i get the version of the relationship between <sonar.version> and <sonarjava.version>

**Comment by slowwalkerlcr** [comment]
> i got the same problem too,it mybe version conflict.
> my sonarqube is 7.6 ,change the "sonar.version" to version 7.6, "sonarjava.version" to version 5.0.1.12818 , will run no error.
> 
> `<sonar.version>7.7</sonar.version> <!-- 7.6 --> <sonarjava.version>5.12.1.17771</sonarjava.version> <!-- 5.0.1.12818 -->`

@ikoopa how can i get the version of the relationship between <sonar.version> and <sonarjava.version>

**Comment by Mycotina** [comment]
> Upgrading `sslr-testing-harness` to the latest version will do
> 
> ```
> <sslr.version>1.23</sslr.version>
> ```

In addition to this, I found out I have to comment out the guava dependency
<dependency>
	<groupId>com.google.guava</groupId>
	<artifactId>guava</artifactId>
	<version>19.0</version>
</dependency>

The rationale for such change can be read here :
https://community.sonarsource.com/t/after-upgrading-sonarjava-plugin-to-5-8-15699-sonar-cant-analyze-class-anymore-guava-issue/3324/14

**Comment by andrea-guarino-sonarsource** [comment]
Hello,
Sorry for the late response and thanks to all the people participating in the discussion!
We don't really monitor GitHub issues and we will disable them soon on this repository. If you need help could you please open a thread on https://community.sonarsource.com/ instead?

Thanks!
