### ISSUE TITLE
Exception when adding MyFirstCustomCheck plugin 

### ISSUE THREAD

**Issue by ysyzygy** [SonarSource/sonar-custom-rules-examples#52]
[sonar.log](https://github.com/SonarSource/sonar-custom-rules-examples/files/4375912/sonar.log)

I installed lastest SonarQube version (sonarqube-8.2.0.32929) on Windows 10 and everything worked fine.
But I follow the instructions and when test the custom plugin, an exception is thrown and nothing works.

It's attached sonar.log.

pom.xml 
	<properties>
		<sslr.version>1.21</sslr.version>
		<gson.version>2.6.2</gson.version>
		<sonar.version>8.2.0.32929</sonar.version>
		<sonarjava.version>6.2.0.21135</sonarjava.version>
	</properties>

Could you please, help me with my problem? I just follow the steps.
Thank you!!

**Comment by m-g-sonar** [comment]
Hello!

The custom-rules example has been moved to the [SonarSource Java Analyzer](https://github.com/SonarSource/sonar-java/tree/master/docs/java-custom-rules-example) repository. This issue should also have been fixed by now.

Cheers,
Michael
