### ISSUE TITLE
SonarQube 8.7 CE Remote debugging does not hit any Check Class

### ISSUE THREAD

**Issue by sbilello** [SonarSource/sonar-custom-rules-examples#63]
Hello!

I tried to debug by placing the jar file under the extensions/plugins
After I started the server with bin/macosx-universal-64/sonar.sh start
I am able to see the rules in the SonarQube UI  as described in the documentation 
I try to perform a maven scan to open remote debugging 
```
 mvnDebug -DskipTests clean install sonar:sonar \                                                                                 ✔  1m 4s   17:22:08
  -Dsonar.projectKey=s3proxy \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=391b5344b7c1c1fea426116bbcb20ac03a6907b2
```
Intellij is able to hit the breakpoint only on the Plugin class but the breakpoint in any of the Rule classes is skipped. 
I don't see even the Print of the Tree in the log. https://github.com/SonarSource/sonar-custom-rules-examples/blob/master/java-custom-rules/src/main/java/org/sonar/samples/java/checks/AvoidAnnotationRule.java#L55

What's missing to make it work? Is there some compatibility issue? Could you please point to a plugin template that can be debugged and that relies on the visitor of the AST? I don't need to deal with the SensorContext that does not contain the information of interest.

**Comment by andrea-guarino-sonarsource** [comment]
Hello  @sbilello,
Sorry for the late response, we don't monitor GitHub issues and we will disable them soon on this repository. If you need help could you please open a thread on https://community.sonarsource.com/ instead?
