### ISSUE TITLE
Problem in the generation of target

### ISSUE THREAD

**Issue by JoseSandovalR** [SonarSource/sonar-custom-rules-examples#67]
Hellou commuity,

I am following the documentation to make custom rules to sound, but when I follow the documentation and try to generate the .jar file I get the following problem:

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.067 s <<< FAILURE! - in org.sonar.samples.java.MyJavaRulesDefinitionTest
[ERROR] org.sonar.samples.java.MyJavaRulesDefinitionTest.test  Time elapsed: 0.059 s  <<< ERROR!
java.lang.IllegalStateException: Can't read resource: org/sonar/l10n/java/rules/java/MyFirstCustomRule.html
        at org.sonar.samples.java.MyJavaRulesDefinitionTest.test(MyJavaRulesDefinitionTest.java:39)
Caused by: java.io.IOException: Resource not found in the classpath: org/sonar/l10n/java/rules/java/MyFirstCustomRule.html
        at org.sonar.samples.java.MyJavaRulesDefinitionTest.test(MyJavaRulesDefinitionTest.java:39)

It is worth mentioning that I have followed the documentation to the letter, on the other hand the myFirstCustomRule.html file is empty

**Comment by andrea-guarino-sonarsource** [comment]
Hello @JoseSandovalR , 
Sorry for the late response, we don't really monitor GitHub issues and we will disable them soon on this repository. If you need help could you please use https://community.sonarsource.com/ instead?
