### ISSUE TITLE
[Question] How to read property value on DoubleDispatchVisitorCheck based my check class?

### ISSUE THREAD

**Issue by SalihKARAHAN** [SonarSource/sonar-custom-rules-examples#9]
Hi, 

I need to reading properties values on my extended check class but depenency injection don't work on consturcutor of check class. Do anybody can suggest me any way:question:

**Comment by agigleux** [comment]
Please ask your questions to http://stackoverflow.com/questions/tagged/sonarqube. 
This "Issues" space is there to report problem you may have regarding the content of the repo itself.
